# -*- coding: utf-8 -*-
"""2026_sw팀프로젝트.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gvTpioxEnzFSXOv7CCfA_CFu7-pgMSov

## 1. 라이브러리 설치
"""

!pip install openmeteo-requests requests-cache retry-requests xgboost scikit-learn joblib -q

import numpy as np
import pandas as pd
import requests_cache
from retry_requests import retry
import openmeteo_requests
import xgboost as xgb
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler
import joblib, json, time, warnings
warnings.filterwarnings('ignore')

print('✅ 완료')

"""## 2. 수도권 격자 생성"""

LAT_MIN, LAT_MAX = 37.0, 37.9
LON_MIN, LON_MAX = 126.4, 127.7
GRID_STEP = 0.05  # 약 5km

lats = np.arange(LAT_MIN, LAT_MAX, GRID_STEP)
lons = np.arange(LON_MIN, LON_MAX, GRID_STEP)

grid_points = [{'lat': round(la, 4), 'lon': round(lo, 4)}
               for la in lats for lo in lons]
df_grid = pd.DataFrame(grid_points)

print(f'격자 포인트: {len(df_grid)}개 ({len(lats)} x {len(lons)})')

"""## 3. Open-Meteo 기상 데이터 수집"""

cache_session = requests_cache.CachedSession('.cache', expire_after=3600)
retry_session = retry(cache_session, retries=5, backoff_factor=0.2)
openmeteo = openmeteo_requests.Client(session=retry_session)

def fetch_weather(lat, lon, days_back=30):
    from datetime import datetime, timedelta
    end   = datetime.now().strftime('%Y-%m-%d')
    start = (datetime.now() - timedelta(days=days_back)).strftime('%Y-%m-%d')

    params = {
        'latitude': lat, 'longitude': lon,
        'hourly': [
            'temperature_2m',
            'relativehumidity_2m',
            'windspeed_10m',
            'shortwave_radiation',
            'et0_fao_evapotranspiration',
            'precipitation',
        ],
        'start_date': start, 'end_date': end,
        'timezone': 'Asia/Seoul'
    }
    try:
        r = openmeteo.weather_api('https://api.open-meteo.com/v1/forecast', params=params)[0].Hourly()
        return {
            'temp_mean':  float(np.nanmean(r.Variables(0).ValuesAsNumpy())),
            'temp_max':   float(np.nanmax(r.Variables(0).ValuesAsNumpy())),
            'humidity':   float(np.nanmean(r.Variables(1).ValuesAsNumpy())),
            'windspeed':  float(np.nanmean(r.Variables(2).ValuesAsNumpy())),
            'radiation':  float(np.nanmean(r.Variables(3).ValuesAsNumpy())),
            'evapotrans': float(np.nanmean(r.Variables(4).ValuesAsNumpy())),
            'precip':     float(np.nansum(r.Variables(5).ValuesAsNumpy())),
        }
    except:
        return None

# ── 수집 범위 설정 ─────────────────────────────
# 테스트: 300개 / 전체: len(df_grid) 로 변경
SAMPLE_SIZE = 300

records = []
for i, row in df_grid.head(SAMPLE_SIZE).iterrows():
    w = fetch_weather(row['lat'], row['lon'])
    if w:
        w.update({'lat': row['lat'], 'lon': row['lon']})
        records.append(w)
    if (i+1) % 10 == 0:
        print(f'  {i+1}/{SAMPLE_SIZE} 수집 완료')
    time.sleep(0.1)

df = pd.DataFrame(records)
print(f'\n✅ 기상 데이터: {len(df)}개 포인트')
print(df.describe())

"""## 4. 도시 특성 변수 생성 (NDVI, 건물밀도, 불투수면적, 인구밀도)"""

# 서울 시청 기준 거리 → 도시 특성 추정
# 실제 서비스: Google Earth Engine(NDVI), 국토부 토지이용 데이터로 대체 권장
SEOUL = (37.5665, 126.9780)

def dist_from_seoul(lat, lon):
    return ((lat - SEOUL[0])**2 + (lon - SEOUL[1])**2) ** 0.5

np.random.seed(42)
df['dist']        = df.apply(lambda r: dist_from_seoul(r['lat'], r['lon']), axis=1)
df['ndvi']        = np.clip(0.15 + df['dist'] * 1.8  + np.random.normal(0, 0.05, len(df)), 0.05, 0.85)
df['build_dens']  = np.clip(0.80 - df['dist'] * 2.5  + np.random.normal(0, 0.05, len(df)), 0.05, 0.95)
df['imperv_surf'] = np.clip(0.85 - df['dist'] * 2.0  + np.random.normal(0, 0.06, len(df)), 0.10, 0.95)
df['pop_density'] = np.clip(25000 - df['dist']*50000  + np.random.normal(0, 1000, len(df)), 200, 30000)

print('변수별 기초통계:')
print(df[['ndvi','build_dens','imperv_surf','pop_density']].describe().round(3))

"""## 5. UHI Index 레이블 계산"""

# 농촌 기준온도: NDVI > 0.5인 격자의 평균 기온
rural = df[df['ndvi'] > 0.5]
T_rural = rural['temp_mean'].mean() if len(rural) > 0 else df['temp_mean'].mean()

df['uhi_index'] = df['temp_mean'] - T_rural

print(f'농촌 기준온도: {T_rural:.2f}°C')
print(f'UHI Index — mean: {df["uhi_index"].mean():.3f}°C  max: {df["uhi_index"].max():.3f}°C')
print(f'양수(열섬) 비율: {(df["uhi_index"] > 0).mean()*100:.1f}%')

"""## 6. 학습 데이터 분할"""

FEATURES = [
    'ndvi', 'build_dens', 'imperv_surf', 'pop_density',
    'humidity', 'windspeed', 'radiation', 'evapotrans',
    'lat', 'lon'
]
TARGET = 'uhi_index'

df_model = df[FEATURES + [TARGET]].dropna()
X = df_model[FEATURES].values
y = df_model[TARGET].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f'train: {len(X_train)}  test: {len(X_test)}')

"""## 7. 모델 학습"""

# ── XGBoost ───────────────────────────────────
xgb_model = xgb.XGBRegressor(
    n_estimators=300, max_depth=6,
    learning_rate=0.05, subsample=0.8,
    colsample_bytree=0.8, random_state=42, verbosity=0
)
xgb_model.fit(X_train, y_train)

# ── RandomForest ──────────────────────────────
rf_model = RandomForestRegressor(
    n_estimators=200, max_depth=10,
    min_samples_split=4, random_state=42, n_jobs=-1
)
rf_model.fit(X_train, y_train)

# ── 앙상블 예측 (XGB 60% + RF 40%) ───────────
y_pred = 0.6 * xgb_model.predict(X_test) + 0.4 * rf_model.predict(X_test)

# ── 성능 출력 ─────────────────────────────────
def evaluate(name, yt, yp):
    print(f'{name:22s} RMSE={np.sqrt(mean_squared_error(yt,yp)):.4f}  '
          f'MAE={mean_absolute_error(yt,yp):.4f}  R²={r2_score(yt,yp):.4f}')

evaluate('XGBoost',          y_test, xgb_model.predict(X_test))
evaluate('RandomForest',     y_test, rf_model.predict(X_test))
evaluate('앙상블 (최종)',     y_test, y_pred)

# ── K-Fold 교차검증 (앙상블 기준 XGB 단독) ────
kf_scores = cross_val_score(xgb_model, X, y, cv=5, scoring='r2')
print(f'\n5-Fold CV R²: {kf_scores.mean():.4f} ± {kf_scores.std():.4f}')

"""## 8. 특성 중요도 출력 (텍스트)"""

imp = sorted(zip(FEATURES, xgb_model.feature_importances_),
             key=lambda x: x[1], reverse=True)

print('특성 중요도 (XGBoost):')
for feat, score in imp:
    bar = '█' * int(score * 100)
    print(f'  {feat:18s} {score:.4f}  {bar}')

"""## 9. 모델 저장"""

joblib.dump(xgb_model, 'uhi_xgb.pkl')
joblib.dump(rf_model,  'uhi_rf.pkl')

meta = {
    'features': FEATURES,
    't_rural_baseline': float(T_rural),
    'version': '1.0.0',
    'region': '수도권',
    'grid_step_deg': GRID_STEP,
    'ensemble_weights': {'xgb': 0.6, 'rf': 0.4}
}
with open('uhi_meta.json', 'w', encoding='utf-8') as f:
    json.dump(meta, f, ensure_ascii=False, indent=2)

print('저장 완료:')
print('  uhi_xgb.pkl   — XGBoost')
print('  uhi_rf.pkl    — RandomForest')
print('  uhi_meta.json — 메타데이터')

from google.colab import drive
drive.mount('/content/drive')

import shutil
shutil.copy('uhi_xgb.pkl',   '/content/drive/MyDrive/uhi_xgb.pkl')
shutil.copy('uhi_rf.pkl',    '/content/drive/MyDrive/uhi_rf.pkl')
shutil.copy('uhi_meta.json', '/content/drive/MyDrive/uhi_meta.json')
print('✅ 구글 드라이브 저장 완료')

"""## 10. 단일 포인트 예측 테스트"""

def predict_uhi(lat, lon, ndvi, build_dens, imperv_surf, pop_density,
                model_xgb=None, model_rf=None, meta_path='uhi_meta.json'):
    """
    단일 포인트 UHI 예측 함수
    기상 데이터는 실시간으로 Open-Meteo에서 가져옴
    """
    with open(meta_path, encoding='utf-8') as f:
        meta = json.load(f)

    # 실시간 기상 수집
    w = fetch_weather(lat, lon, days_back=3)
    if w is None:
        raise ValueError('기상 데이터 수집 실패')

    X_input = np.array([[
        ndvi, build_dens, imperv_surf, pop_density,
        w['humidity'], w['windspeed'], w['radiation'], w['evapotrans'],
        lat, lon
    ]])

    if model_xgb is None: model_xgb = joblib.load('uhi_xgb.pkl')
    if model_rf  is None: model_rf  = joblib.load('uhi_rf.pkl')

    uhi = 0.6 * model_xgb.predict(X_input)[0] + 0.4 * model_rf.predict(X_input)[0]

    grade = ('심각' if uhi >= 3 else '높음' if uhi >= 2
             else '중간' if uhi >= 1 else '낮음' if uhi >= 0 else '없음')

    return {
        'lat': lat, 'lon': lon,
        'uhi_index': round(float(uhi), 3),
        'uhi_grade': grade,
        'current_temp': round(w['temp_mean'], 1),
        'estimated_urban_temp': round(w['temp_mean'] + uhi, 1),
    }

# 테스트: 강남구 좌표
result = predict_uhi(
    lat=37.5172, lon=127.0473,
    ndvi=0.15, build_dens=0.85,
    imperv_surf=0.90, pop_density=22000,
    model_xgb=xgb_model, model_rf=rf_model
)
print('강남구 예측 결과:')
for k, v in result.items():
    print(f'  {k}: {v}')

"""## 1. 라이브러리 설치"""

!pip install fastapi uvicorn pyngrok openmeteo-requests requests-cache retry-requests joblib nest-asyncio -q
print('✅ 완료')

"""## 2. 이전 노트북 모델 파일 확인"""

import os

required = ['uhi_xgb.pkl', 'uhi_rf.pkl', 'uhi_meta.json']
for f in required:
    status = '✅' if os.path.exists(f) else '❌ 없음 — 이전 노트북 9번 셀 먼저 실행하세요'
    print(f'{status}  {f}')

"""## 3. FastAPI 앱 정의"""

!pip install openmeteo-requests requests-cache retry-requests joblib -q

import json, joblib, numpy as np
import requests_cache, openmeteo_requests
from retry_requests import retry
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from pydantic import BaseModel, Field
from google.colab import drive

drive.mount('/content/drive')

# ── 모델 로드 (구글 드라이브) ─────────────────
xgb_model = joblib.load('/content/drive/MyDrive/uhi_xgb.pkl')
rf_model  = joblib.load('/content/drive/MyDrive/uhi_rf.pkl')
with open('/content/drive/MyDrive/uhi_meta.json', encoding='utf-8') as f:
    META = json.load(f)

# ── Open-Meteo 클라이언트 ─────────────────────
cache_session = requests_cache.CachedSession('.cache', expire_after=600)
retry_session = retry(cache_session, retries=3, backoff_factor=0.2)
openmeteo     = openmeteo_requests.Client(session=retry_session)

def fetch_weather_realtime(lat, lon):
    params = {
        'latitude': lat, 'longitude': lon,
        'current': [
            'temperature_2m', 'relativehumidity_2m',
            'windspeed_10m',  'shortwave_radiation',
        ],
        'timezone': 'Asia/Seoul'
    }
    r = openmeteo.weather_api('https://api.open-meteo.com/v1/forecast', params=params)[0]
    c = r.Current()
    return {
        'temp_mean':  float(c.Variables(0).Value()),
        'humidity':   float(c.Variables(1).Value()),
        'windspeed':  float(c.Variables(2).Value()),
        'radiation':  float(c.Variables(3).Value()),
        'evapotrans': 0.0,
    }

def uhi_grade(uhi):
    if uhi >= 3: return '심각'
    if uhi >= 2: return '높음'
    if uhi >= 1: return '중간'
    if uhi >= 0: return '낮음'
    return '없음'

# ── FastAPI 앱 (app은 딱 한 번만) ────────────
class NgrokMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        response = await call_next(request)
        response.headers['ngrok-skip-browser-warning'] = 'true'
        response.headers['Access-Control-Allow-Origin'] = '*'
        response.headers['Access-Control-Allow-Headers'] = '*'
        response.headers['Access-Control-Allow-Methods'] = '*'
        return response

app = FastAPI(title='수도권 열섬 예측 API', version='1.0.0')
app.add_middleware(NgrokMiddleware)
app.add_middleware(CORSMiddleware, allow_origins=['*'], allow_methods=['*'], allow_headers=['*'])

class PredictRequest(BaseModel):
    lat:         float = Field(..., example=37.5172)
    lon:         float = Field(..., example=127.0473)
    ndvi:        float = Field(..., ge=0, le=1, example=0.15)
    build_dens:  float = Field(..., ge=0, le=1, example=0.85)
    imperv_surf: float = Field(..., ge=0, le=1, example=0.90)
    pop_density: float = Field(..., ge=0,       example=22000)

@app.get('/')
def root(): return {'status': 'ok'}

@app.get('/health')
def health(): return {'status': 'healthy'}

@app.post('/predict')
async def predict(req: PredictRequest):
    try:
        w = fetch_weather_realtime(req.lat, req.lon)
    except Exception as e:
        raise HTTPException(status_code=503, detail=f'기상 데이터 수집 실패: {e}')
    X = np.array([[
        req.ndvi, req.build_dens, req.imperv_surf, req.pop_density,
        w['humidity'], w['windspeed'], w['radiation'], w['evapotrans'],
        req.lat, req.lon
    ]])
    uhi = float(0.6 * xgb_model.predict(X)[0] + 0.4 * rf_model.predict(X)[0])
    return {
        'lat': req.lat, 'lon': req.lon,
        'uhi_index':            round(uhi, 3),
        'uhi_grade':            uhi_grade(uhi),
        'current_temp':         round(w['temp_mean'], 1),
        'estimated_urban_temp': round(w['temp_mean'] + uhi, 1),
        'weather': {
            'humidity':  round(w['humidity'], 1),
            'windspeed': round(w['windspeed'], 1),
            'radiation': round(w['radiation'], 1),
        }
    }

print('✅ FastAPI 앱 정의 완료')

"""## 4. ngrok 토큰 설정 & 서버 실행"""

# ⚠️ https://ngrok.com 무료 가입 후 토큰 발급
# Dashboard → Your Authtoken → 복사
from pyngrok import ngrok
ngrok.kill()  # 기존 터널 전부 종료
NGROK_TOKEN = '3EormKtmqYprew91kmlOPuUEW3u_61TWZCNPG6mETsgGES9qu'  # ← 여기에 입력

import nest_asyncio, uvicorn, threading
from pyngrok import ngrok, conf

nest_asyncio.apply()
conf.get_default().auth_token = NGROK_TOKEN

# 기존 터널 정리
ngrok.kill()

# 서버 백그라운드 실행
def run():
    uvicorn.run(app, host='0.0.0.0', port=8000, log_level='error')

t = threading.Thread(target=run, daemon=True)
t.start()

import time; time.sleep(2)

# ngrok 터널 생성
public_url = ngrok.connect(8000).public_url

print('🚀 API 서버 실행 중!')
print(f'   공개 URL : {public_url}')
print(f'   Swagger  : {public_url}/docs')
print(f'   예측 API : {public_url}/predict  (POST)')
print('\n📱 이 URL을 앱에서 사용하세요')

import os
os.system('kill -9 $(lsof -t -i:8000)')

from pyngrok import ngrok
ngrok.kill()

print('✅ 정리 완료')

"""## 5. API 동작 테스트 (파이썬으로 직접 호출)"""

import requests

# 테스트 포인트 3곳
test_cases = [
    {'name': '강남구',  'lat': 37.5172, 'lon': 127.0473, 'ndvi': 0.12, 'build_dens': 0.88, 'imperv_surf': 0.92, 'pop_density': 22000},
    {'name': '종로구',  'lat': 37.5726, 'lon': 126.9794, 'ndvi': 0.18, 'build_dens': 0.80, 'imperv_surf': 0.85, 'pop_density': 15000},
    {'name': '가평군',  'lat': 37.8314, 'lon': 127.5097, 'ndvi': 0.68, 'build_dens': 0.10, 'imperv_surf': 0.15, 'pop_density': 1200},
]

print(f'{"지역":8s} {"UHI":>8s} {"등급":>6s} {"현재기온":>8s} {"체감도시온도":>10s}')
print('-' * 48)

for tc in test_cases:
    name = tc.pop('name')
    r = requests.post(f'{public_url}/predict', json=tc).json()
    print(f'{name:8s} {r["uhi_index"]:>+8.3f}°C {r["uhi_grade"]:>6s} '
          f'{r["current_temp"]:>7.1f}°C {r["estimated_urban_temp"]:>9.1f}°C')

